#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"load-balancer-example"},"name":"hello-world","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app.kubernetes.io/name":"load-balancer-example"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"load-balancer-example"}},"spec":{"containers":[{"image":"gcr.io/google-samples/node-hello:1.0","name":"hello-world","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2022-11-14T20:30:21Z"
  generation: 1
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
  namespace: default
  resourceVersion: "4609316"
  uid: 889db3d3-a618-4142-b3df-fc9b98a8785e
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2022-11-14T20:31:47Z"
    lastUpdateTime: "2022-11-14T20:31:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-11-14T20:30:22Z"
    lastUpdateTime: "2022-11-14T20:31:47Z"
    message: ReplicaSet "hello-world-6755976cfc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
